dist:
  bionic

language:
  minimal

install:
  ./.travis/install.sh

script:
  ./.travis/build.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  fqdn: tools.ashenm.ml

after_deploy:
  ./.travis/culminate.sh

notifications:
  slack:
    secure: PWIen1oGRCeig/sYTt35kj4KDO0BtdOtdwPAd/fIfVKn3ElPJu+wj1pMAsCqjoygOt7CF0Aqfq0Smvs5cJbOv2VkZoE/sRpo+9rGyPfgg0h8IZZqcVf3GYP6aSOjUmlJy0e1MY/wqPRwhPj4YOHekIx0beyJdpTg2KA33fIGQrO3JlGp6zJ7ng46dsuWwzBSaMoMQfJfisiJKFFOgn6z6VXzlZxObas/awh2axnhPXZCjE04FmuXdzbk/vqucwMKRj1pr81LqteT7Cp4Xeg62rMOuoe0g/k9ScpHfbtNQeCWsE2YEYbio1p4MI0/g8QcMt8iVbJOSdXGYUShOhpHZ+svESwKz6bt2GJah3I2J5J6FwagJWcfKOej2T+rPcmTVnWnvO96rG3HJxrQHlARqnAUn6UkasuTAJe6WWmTlOmEKJ4ZDaLsVAhRFPCmmm9UfM/D5wQ+YyqpacBwymEVQSni8M0T0+N9LnSu4D0wmm1E+Sr4uny/tAdOWvlXSXVUFlThNF6S3jocnhF3Tb55ky+wF2k9H83EY8kxtitaHYEqf4gz+zERUHzIKjv/uhLqnagJSwYlbJkm6nlUPFP9CA1QVqzrvPmAZrwgtCuWtWGXc1hGqhU4l4DWu6KaKv/+iyr1DMUI4rJXerHnLHmLqby6JFUr8DPIUjdjPTDE5M8=
