safe: ture
timezone: "Etc/UTC"
encoding: "utf-8"
url: "https://ashenm.github.io/tools"

lang: "en"
title: "Demonstration Tools"
author: "Ashen Gunaratne"
email: "mail@ashenm.ml"
keywords: "ashen, gunaratne, ashen m. gunaratne, educational, tools, materials"
desc: "A collection of miscellanies instructional tools and materials"

source: ./src

exclude:
  - CNAME
  - Makefile
  - requirements.txt
  - scripts

defaults:
  scope:
    path: ""
    type: "pages"
  values:
    layout: "default"
